/* eslint-disable react-hooks/set-state-in-effect, react-hooks/immutability, react-hooks/purity */
"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Filter, RefreshCw, Save } from "lucide-react";
import { formatCurrency, formatNumber } from "@/lib/utils";

type Segment = { id: string; name: string; city: string | null; min_total_rides: number | null; inactive_days: number | null; min_spend: number | null; estimated_count: number; is_active: boolean; created_at: string };
const inputClass = "w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm outline-none focus:border-orange-400";

export default function SegmentsPage() {
  const [segments, setSegments] = useState<Segment[]>([]); const [loading, setLoading] = useState(true); const [name, setName] = useState("Users inactive 60 days"); const [city, setCity] = useState(""); const [rides, setRides] = useState(""); const [inactive, setInactive] = useState("60"); const [spend, setSpend] = useState("");
  const load = async () => { setLoading(true); const { data } = await supabase.from("customer_segments").select("*").order("created_at", { ascending: false }); setSegments((data || []) as Segment[]); setLoading(false); };
  useEffect(() => { load(); }, []);
  const save = async () => { const { error } = await supabase.from("customer_segments").insert({ name, city: city || null, min_total_rides: rides ? Number(rides) : null, inactive_days: inactive ? Number(inactive) : null, min_spend: spend ? Number(spend) : null, is_active: true }); if (error) return alert(error.message); load(); };
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-zinc-900">Customer Segments</h1><p className="text-sm text-zinc-500">Filter riders by city, rides, frequency, last ride date and spend.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
    <div className="grid gap-6 lg:grid-cols-[360px_1fr]"><div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-black"><Filter className="h-4 w-4 text-orange-600"/>Create Segment</h2><div className="space-y-3"><Field label="Name"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="City"><input className={inputClass} value={city} onChange={e=>setCity(e.target.value)} placeholder="Cape Town, Lilongwe..."/></Field><div className="grid grid-cols-3 gap-2"><Field label="Min rides"><input type="number" className={inputClass} value={rides} onChange={e=>setRides(e.target.value)}/></Field><Field label="Inactive days"><input type="number" className={inputClass} value={inactive} onChange={e=>setInactive(e.target.value)}/></Field><Field label="Min spend"><input type="number" className={inputClass} value={spend} onChange={e=>setSpend(e.target.value)}/></Field></div><button onClick={save} className="flex w-full items-center justify-center gap-2 rounded-xl bg-orange-600 py-3 text-sm font-black text-white"><Save className="h-4 w-4"/>Save Segment</button></div></div>
    <div className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-sm"><thead className="bg-zinc-50 text-left text-zinc-500"><tr><th className="px-4 py-3">Segment</th><th className="px-4 py-3">Rules</th><th className="px-4 py-3 text-right">Estimated Users</th><th className="px-4 py-3">Status</th></tr></thead><tbody>{loading ? <tr><td colSpan={4} className="p-8 text-center text-zinc-400">Loading...</td></tr> : segments.map(s => <tr key={s.id} className="border-t"><td className="px-4 py-3 font-bold">{s.name}</td><td className="px-4 py-3 text-xs text-zinc-500">{s.city || "All cities"} · {s.min_total_rides ? `${s.min_total_rides}+ rides` : "Any rides"} · {s.inactive_days ? `inactive ${s.inactive_days}d` : "any activity"} · {s.min_spend ? `${formatCurrency(s.min_spend)}+ spend` : "any spend"}</td><td className="px-4 py-3 text-right">{formatNumber(s.estimated_count || 0)}</td><td className="px-4 py-3"><span className="rounded-full bg-orange-100 px-2 py-1 text-xs font-bold text-orange-700">{s.is_active ? "Active" : "Inactive"}</span></td></tr>)}</tbody></table></div></div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-xs font-bold text-zinc-600">{label}</span>{children}</label>; }
