"use client";

import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
import { Award, Plus, RefreshCw } from "lucide-react";

const inputClass = "w-full rounded-xl border border-zinc-200 bg-zinc-50 px-3 py-2 text-sm outline-none focus:border-orange-400";
type Tier = { id: string; name: string; min_rides: number; discount_percent: number; priority_support: boolean; voucher_amount: number; is_active: boolean; sort_order: number };

export default function LoyaltyPage() {
  const [tiers, setTiers] = useState<Tier[]>([]); const [loading, setLoading] = useState(true); const [name, setName] = useState("Silver"); const [rides, setRides] = useState("10"); const [discount, setDiscount] = useState("5"); const [voucher, setVoucher] = useState("0"); const [priority, setPriority] = useState(false);
  const load = async () => { setLoading(true); const { data } = await supabase.from("loyalty_tiers").select("*").order("sort_order"); setTiers((data || []) as Tier[]); setLoading(false); };
  useEffect(() => { load(); }, []);
  const save = async () => { const { error } = await supabase.from("loyalty_tiers").insert({ name, min_rides: Number(rides) || 0, discount_percent: Number(discount) || 0, voucher_amount: Number(voucher) || 0, priority_support: priority, is_active: true, sort_order: tiers.length + 1 }); if (error) return alert(error.message); load(); };
  const toggle = async (t: Tier) => { await supabase.from("loyalty_tiers").update({ is_active: !t.is_active, updated_at: new Date().toISOString() }).eq("id", t.id); load(); };
  return <div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-2xl font-black text-zinc-900">Loyalty Program</h1><p className="text-sm text-zinc-500">Manage Silver, Gold and Platinum rider benefits.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border bg-white px-4 py-2 text-sm font-bold"><RefreshCw className="h-4 w-4"/>Refresh</button></div>
    <div className="grid gap-6 lg:grid-cols-[340px_1fr]"><div className="rounded-2xl border bg-white p-5"><h2 className="mb-4 flex items-center gap-2 font-black"><Plus className="h-4 w-4 text-orange-600"/>Add Tier</h2><div className="space-y-3"><Field label="Tier name"><input className={inputClass} value={name} onChange={e=>setName(e.target.value)}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Min rides"><input type="number" className={inputClass} value={rides} onChange={e=>setRides(e.target.value)}/></Field><Field label="Discount %"><input type="number" className={inputClass} value={discount} onChange={e=>setDiscount(e.target.value)}/></Field></div><Field label="Ride voucher amount"><input type="number" className={inputClass} value={voucher} onChange={e=>setVoucher(e.target.value)}/></Field><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={priority} onChange={e=>setPriority(e.target.checked)}/>Priority support</label><button onClick={save} className="w-full rounded-xl bg-orange-600 py-3 text-sm font-black text-white">Save Tier</button></div></div>
    <div className="grid gap-3 md:grid-cols-3">{loading ? <div className="rounded-2xl border bg-white p-8 text-center text-zinc-400">Loading...</div> : tiers.map(t => <div key={t.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><Award className="h-7 w-7 text-orange-500"/><span className={`rounded-full px-2 py-1 text-xs font-bold ${t.is_active ? "bg-orange-100 text-orange-700" : "bg-zinc-100 text-zinc-500"}`}>{t.is_active ? "Active" : "Inactive"}</span></div><h3 className="mt-4 text-xl font-black">{t.name}</h3><p className="mt-1 text-sm text-zinc-500">From {t.min_rides} rides</p><div className="mt-4 space-y-2 text-sm"><p>Discount: <b>{t.discount_percent}%</b></p><p>Voucher: <b>MWK {Number(t.voucher_amount || 0).toLocaleString()}</b></p><p>Priority support: <b>{t.priority_support ? "Yes" : "No"}</b></p></div><button onClick={()=>toggle(t)} className="mt-5 w-full rounded-xl bg-zinc-100 py-2 text-sm font-bold">{t.is_active ? "Disable" : "Enable"}</button></div>)}</div></div></div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="mb-1 block text-xs font-bold text-zinc-600">{label}</span>{children}</label>; }
